version: "3.8"

services:
  app:
    build: .
    container_name: elbot
    ports:
      - "3000:3000" # Проброс порта
    networks:
      - app_network
    env_file:
      - stack.env

networks:
  app_network:
    driver: bridge
